--- # OWASP ZAP automation configuration file, for more details see https://www.zaproxy.com/docs/(TBA)
env:                                   # The environment, mandatory
  contexts :                           # List of 1 or more contexts, mandatory
    - name: context 1                  # Name to be used to refer to this context in other jobs, mandatory
      url: https://sonerkapperszaak.nl                            # The top level url, mandatory, everything under this will be included
      authentication:                  # TBA: In time to cover all auth configs
  parameters:
    failOnError: true                  # If set exit on an error         
    failOnWarning: false               # If set exit on a warning
    progressToStdout: true             # If set will write job progress to stdout

jobs:
  - type: addOns                       # Add-on management
    parameters:
      updateAddOns: true               # Update any add-ons that have new versions
    install:                           # A list of non standard add-ons to install from the ZAP Marketplace
    uninstall:                         # A list of standard add-ons to uninstall

  - type: passiveScan-config           # Passive scan configuration
    parameters:
      maxAlertsPerRule: 10             # Int: Maximum number of alerts to raise per rule
      scanOnlyInScope: true            # Bool: Only scan URLs in scope (recommended)
      maxBodySizeInBytesToScan:        # Int: Maximum body size to scan, default: 0 - will scan all messages

  - type: spider                       # The traditional spider - fast but doesnt handle modern apps so well
    parameters:
      context: context 1                        # String: Name of the context to spider, default: first context
      url: https://sonerkapperszaak.nl                             # String: Url to start spidering from, default: first context URL
      failIfFoundUrlsLessThan: 50        # Int: Fail if spider finds less than the specified number of URLs, default: 0
      warnIfFoundUrlsLessThan: 20        # Int: Warn if spider finds less than the specified number of URLs, default: 0
      maxDuration: 0                    # Int: The max time in minutes the spider will be allowed to run for, default: 0 unlimited
      maxDepth: 5                       # Int: The maximum tree depth to explore

  - type: passiveScan-wait             # Passive scan wait for the passive scanner to finish
    parameters:
      maxDuration: 5                   # Int: The max time to wait for the passive scanner, default: 0 unlimited

  - type: report                       # Report generation
    parameters:
      template:                        # String: The template id, default : traditional-html
      reportDir:                       # String: The directory into which the report will be written
      reportFile:                      # String: The report file name pattern, default: {{yyyy-MM-dd}}-ZAP-Report-[[site]]
      reportTitle:                     # String: The report title
      reportDescription:               # String: The report description
